## Instrucciones:

- Descripción del Problema: Imagina que estás trabajando como analista de datos para una empresa que recopila información sobre las ventas diarias de diferentes productos en varias tiendas. Necesitas analizar estos datos para extraer información útil y presentar un resumen de las ventas.

#### Requisitos del Sistema:
-  OK El programa debe generar datos de ventas de manera aleatoria para 10 productos diferentes en 5 tiendas distintas durante 7 días (una semana).
- OK Los datos deben estar almacenados en un array de NumPy de 3 dimensiones (productos, tiendas, días).
- Debes calcular y mostrar la siguiente información:
    - Total de ventas por producto a lo largo de la semana.
    - Total de ventas por tienda a lo largo de la semana.
    - Promedio de ventas por producto por día.
    - Promedio de ventas por tienda por día.
    - Producto con mayor y menor ventas totales en la semana.
    - Tienda con mayor y menor ventas totales en la semana.

#### DATOS

In [1]:
import numpy as np

def generar_datos_ventas(productos, tiendas, dias):
    # Genera datos de ventas aleatorias para el número de productos, tiendas y días especificados
    return np.random.randint(0, 101, (productos, tiendas, dias))

datos = generar_datos_ventas(10, 5, 7)
print(datos)


[[[ 26  48  58  67  81  67  28]
  [ 44   4   0  16  47  83  38]
  [ 90  22  64  75   3   0  96]
  [ 81  68  43  86  11  44  68]
  [ 28  55  41   3  25  92  30]]

 [[ 17  75   4  68  59  76  78]
  [ 79  87  60  77  59  80   4]
  [ 41  57  33  18  43  66  27]
  [ 99  76  86  74  12  48  59]
  [ 35  81  65  33  86  43  36]]

 [[ 75  46  12 100  41  89  69]
  [ 12  90  49  23  63  49  60]
  [100  46  92  29  17  42   0]
  [ 99  30  18  84  41  15  89]
  [ 76  84  19  42  96  20   1]]

 [[ 86  59  50 100   2  46  11]
  [ 11  18  43  10  39  12  74]
  [ 19  78  94  16  47   7  97]
  [ 60   8  29  70  99  27  86]
  [ 91  66  97  75  22  82  95]]

 [[ 44  97  83  50  51   7  96]
  [ 42  37  31  67  64  63 100]
  [ 75  22  75  56  14  14  13]
  [ 72  45  73  12   4  96  33]
  [ 96  89   5  67  43  80   2]]

 [[ 30  71  66   1  46  62  99]
  [ 38  45  15  58  38   2  45]
  [ 11  38  70  38  66  23  76]
  [ 57  19   4   8  52  26  58]
  [ 20  13  57  80  74  16  44]]

 [[ 67   9  26  15  20  82  

#### TOTAL DE VENTAS POR PRODUCTO A LO LARGO DE LA SEMANA

In [33]:
def calcular_totales_ventas_por_producto(datos):
    # Calcula el total de ventas por producto a lo largo de la semana
    return np.sum(datos, axis=(1, 2))

totales_por_producto = calcular_totales_ventas_por_producto(datos)
print("Total de ventas por producto a lo largo de la semana:", totales_por_producto)

Total de ventas por producto a lo largo de la semana: [[2457 2535 2406 2373 2215 2291 2919]]



#### TOTAL DE VENTAS POR TIENDA A LO LARGO DE LA SEMANA

In [34]:
def calcular_totales_ventas_por_tienda(datos):
    # Calcula el total de ventas por tienda a lo largo de la semana
    return np.sum(datos, axis=(0, 2))

totales_por_tienda = calcular_totales_ventas_por_tienda(datos)
print("Total de ventas por tienda a lo largo de la semana:", totales_por_tienda)

Total de ventas por tienda a lo largo de la semana: [[190 319 159 155 240 264 305]
 [177 236 307 240 237 257 323]
 [250 209 242 269  75 267 225]
 [281 405 203 167 270 173 151]
 [210 178 285 156 249 169 226]
 [221 291 271 235 223 202 340]
 [201 222 272 210 307 283 402]
 [401 189 221 393 195 208 264]
 [270 276 240 237 204 234 339]
 [256 210 206 311 215 234 344]]


#### PROMEDIO DE VENTAS POR PRODUCTO POR DIA

In [27]:
def calcular_promedio_ventas_por_producto(datos):
    # Calcula el promedio de ventas por producto por día
    return np.mean(datos, axis=(0, 2))

promedio_por_producto = calcular_promedio_ventas_por_producto(datos)
print("Promedio de ventas por producto por día:", promedio_por_producto)

Promedio de ventas por producto por día: [[38.  63.8 31.8 31.  48.  52.8 61. ]
 [35.4 47.2 61.4 48.  47.4 51.4 64.6]
 [50.  41.8 48.4 53.8 15.  53.4 45. ]
 [56.2 81.  40.6 33.4 54.  34.6 30.2]
 [42.  35.6 57.  31.2 49.8 33.8 45.2]
 [44.2 58.2 54.2 47.  44.6 40.4 68. ]
 [40.2 44.4 54.4 42.  61.4 56.6 80.4]
 [80.2 37.8 44.2 78.6 39.  41.6 52.8]
 [54.  55.2 48.  47.4 40.8 46.8 67.8]
 [51.2 42.  41.2 62.2 43.  46.8 68.8]]


#### PROMEDIO DE VENTAS POR TIENDA POR DIA

In [28]:
def calcular_promedio_ventas_por_tienda(datos):
    # Calcula el promedio de ventas por tienda por día
    return np.mean(datos, axis=(0, 1))

promedio_por_tienda = calcular_promedio_ventas_por_tienda(datos)
print("Promedio de ventas por tienda por día:", promedio_por_tienda)

Promedio de ventas por tienda por día: [[57.2 38.5 55.6 27.5 47.7 58.9 53. ]
 [49.4 52.3 46.6 43.5 37.4 28.8 75.3]
 [48.7 58.9 52.1 64.  60.1 49.3 68.5]
 [50.8 52.  36.  54.6 26.8 50.7 48.8]
 [39.6 51.8 50.3 47.7 49.5 41.4 46.3]]


#### EL PRODUCTO CON MAYOR Y MENOR VENTAS TOTALES EN LA SEMANA

In [30]:
def encontrar_producto_mayor_menor_ventas(totales_por_producto):
    # Encuentra el producto con mayor y menor ventas totales en la semana
    producto_mayor_ventas = np.argmax(totales_por_producto)
    producto_menor_ventas = np.argmin(totales_por_producto)
    return producto_mayor_ventas, producto_menor_ventas

producto_mayor_ventas, producto_menor_ventas = encontrar_producto_mayor_menor_ventas(totales_por_producto)
print(f"Producto con mayor ventas: Producto {producto_mayor_ventas}")
print(f"Producto con menor ventas: Producto {producto_menor_ventas}")

Producto con mayor ventas: Producto 22
Producto con menor ventas: Producto 18


#### TIENDA CON MAYOR Y MENOR VENTAS TOTALES EN LA SEMANA

In [31]:
def encontrar_tienda_mayor_menor_ventas(totales_por_tienda):
    # Encuentra la tienda con mayor y menor ventas totales en la semana
    tienda_mayor_ventas = np.argmax(totales_por_tienda)
    tienda_menor_ventas = np.argmin(totales_por_tienda)
    return tienda_mayor_ventas, tienda_menor_ventas

tienda_mayor_ventas, tienda_menor_ventas = encontrar_tienda_mayor_menor_ventas(totales_por_tienda)
print(f"Tienda con mayor ventas: Tienda {tienda_mayor_ventas}")
print(f"Tienda con menor ventas: Tienda {tienda_menor_ventas}")


Tienda con mayor ventas: Tienda 13
Tienda con menor ventas: Tienda 25
